name: Sync Email Aliases

on: [push]

jobs:
  sync-email-aliases:

    runs-on: ubuntu-latest

    env:
      HYPHA_RESTRICTED_TOKEN: ${{ secrets.HYPHA_RESTRICTED_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Sync email aliases
      run: |
        pipenv run python sync-email-aliases.py email-aliases.yml --api-key $HYPHA_RESTRICTED_TOKEN
